# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    #- run: npm run build --if-present
    - run: npm test
    - name: Jest Annotations & Coverage
      # You may pin to the exact commit or the version.
      # uses: mattallty/jest-github-action@43bbcd073fa43a927322f188220b6592acae003b
      uses: mattallty/jest-github-action@v1.0.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # The test command to run
        test-command: npm testcov
    - name: Jest Code Coverage Report
      # You may pin to the exact commit or the version.
      # uses: ziishaned/jest-reporter-action@872c1051350ecaf625ba2490d68e7cb63854b44c
      uses: ziishaned/jest-reporter-action@0.1.1
     # with:
        # Github token
      #  github-token: ${{ secrets.GITHUB_TOKEN }}
        # Specify a command to run the tests
       # test-command: "npm run testcov" 
